import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {handleApi} from '../src/game-api.mjs';
function fixture(){const sqlite=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(x=>x.endsWith('.sql')))sqlite.exec(readFileSync('drizzle/'+file,'utf8'));const db={prepare(sql){let args=[];const p={bind(...a){args=a;return p;},async first(){return sqlite.prepare(sql).get(...args)||null;},async run(){return sqlite.prepare(sql).run(...args);},async all(){return {results:sqlite.prepare(sql).all(...args)};}};return p;},async batch(q){sqlite.exec('BEGIN');try{const results=[];for(const p of q)results.push(await p.all());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};return {db,sqlite};}
const env={ADMIN_PASSWORD_HASH:createHash('sha256').update('test-password-only').digest('hex')};
async function call(db,path,body,cookies='',origin='https://game.test'){const r=await handleApi(new Request('https://game.test/api/'+path,{method:body?'POST':'GET',headers:{cookie:cookies,origin,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),db,env);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function boot(db){const b=await call(db,'bootstrap');assert.equal(b.status,200);return b.cookie;}
const save={bank:630,level:1,lab:{stocks:{basic:5}},round:{id:'resume-me'},updatedAt:123};
test('cloud save persists, isolates players, and atomically rejects stale concurrent revisions',async()=>{const {db,sqlite}=fixture();try{const a=await boot(db),b=await boot(db);const writes=await Promise.all([call(db,'save',{revision:0,save},a),call(db,'save',{revision:0,save:{...save,bank:99}},a)]);assert.deepEqual(writes.map(r=>r.status).sort(),[200,409]);const loaded=await call(db,'bootstrap',null,a);assert.equal(loaded.data.save.bank,630);assert.equal((await call(db,'bootstrap',null,b)).data.save,null);assert.equal((await call(db,'save',{revision:7,save},b)).status,409);assert.equal((await call(db,'save',{revision:1,save:{...save,bank:-1}},a)).status,400);}finally{sqlite.close();}});
test('admin is private, rejects cross-origin writes and rate-limits login',async()=>{const {db,sqlite}=fixture();try{assert.equal((await call(db,'admin/stats')).status,401);assert.equal((await call(db,'admin/login',{password:'test-password-only'},'','https://evil.test')).status,403);for(let i=0;i<10;i++)assert.equal((await call(db,'admin/login',{password:'wrong'})).status,401);assert.equal((await call(db,'admin/login',{password:'test-password-only'})).status,429);}finally{sqlite.close();}});
test('online time includes idle, merges overlapping tabs, terminal visits and rounds stay terminal',async()=>{const {db,sqlite}=fixture();try{const a=await boot(db),b=await boot(db);const p=a.split('=')[1],now=Date.now()/1000;sqlite.prepare('INSERT INTO visits VALUES(?,?,?,?,?,?)').run('visit-one',p,now-100,now,100,1);sqlite.prepare('INSERT INTO visits VALUES(?,?,?,?,?,?)').run('visit-two',p,now-50,now,50,1);await call(db,'visit',{id:'visit-one',elapsed:200},a);assert.equal(sqlite.prepare("SELECT elapsed FROM visits WHERE id='visit-one'").get().elapsed,100);assert.equal((await call(db,'visit',{id:'visit-one',elapsed:20},b)).status,403);const round={id:'round-one',status:'completed',duration:30,caught:2,delivered:2,escaped:6,total:8,demo:false};await call(db,'round',round,a);await call(db,'round',{...round,status:'playing',duration:31},a);assert.equal(sqlite.prepare('SELECT status FROM rounds').get().status,'completed');assert.equal((await call(db,'round',round,b)).status,403);const login=await call(db,'admin/login',{password:'test-password-only'});assert.equal(login.status,200);const report=await call(db,'admin/stats',null,login.cookie);assert.equal(report.status,200);assert.equal(report.data.summary.players,2);assert.equal(report.data.summary.totalSeconds,100);assert.equal(report.data.summary.averageSeconds,50);assert.equal(report.data.summary.completedRounds,1);assert.equal(report.data.daily.length,7);await call(db,'admin/logout',{},login.cookie);assert.equal((await call(db,'admin/stats',null,login.cookie)).status,401);}finally{sqlite.close();}});
